
import os
ROOT = os.path.join(os.path.dirname(__file__))
CSS_STYLE = os.path.join(ROOT, "style/style.css")
CSS_DIR = os.path.join(ROOT, "style")
DATA_DIR = os.path.join(ROOT, "data")
CONFIG_DIR = os.path.join(ROOT, "etc")
DRIVERS_DIR = os.path.join(ROOT, "drivers")
DATA_FILE = os.path.join(DATA_DIR, "data.db")
ICON_DIR = os.path.join(ROOT, "resource/icons")
ETC = os.path.join(ROOT, "etc")
CONFIG_PATH = os.path.join(ETC, "default.json")
TEST_DIR = os.path.join(ROOT, "tests", "data")
DATA_GRAPH = os.path.join(ROOT, "data", "graphics")
TEMP_GRAPH = os.path.join(DATA_GRAPH, "temp_graph")
LOG_DIR = os.path.join(ROOT, "log")